<?php
/** @var $block Emagento\Comments\Block\ReviewList */
?>
<div id="reviews-list" data-bind="scope: 'reviews'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#reviews-list": {
        "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
    }
}
</script>

<div id="reviews-popup-full" class="reviews-popup-full" data-bind="scope: 'reviews_full'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#reviews-popup-full": {
        "Magento_Ui/js/core/app": {
            "components": {
                "reviews_full": {
                    "component": "Emagento_Comments/js/reviews_full",
                    "config": {
                        "template": "Emagento_Comments/reviews_full_template",
                        "count": 10
                    }
                }
            }
        }
    }
}
</script>
