<?php

namespace Emagento\Comments\Ui\Component\Listing\Columns;

use Amazon\Core\Helper\Data;
use Magento\Ui\Component\Listing\Columns\Column;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Framework\Data\OptionSourceInterface;
use Emagento\Comments\Helper\Data as DataSource;

class Source extends Column implements OptionSourceInterface
{
    /**
     * @var DataSource
     */
    public $source;

    public function __construct(
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        array $components = [],
        array $data = [],
        DataSource $source
    ) {
        parent::__construct($context, $uiComponentFactory, $components, $data);
        $this->source = $source;
    }

    public function prepareDataSource(array $dataSource)
    {
        return parent::prepareDataSource($dataSource); // TODO: Change the autogenerated stub
    }

    public function toOptionArray()
    {
        return $this->source->getSourceOptionArray();
    }
}
